//CART

/*
    ID
    ARRAY OF PRODUCTS = PRODUCT, CANTIDAD
    ARRAY OF CUSTOM PRODUCTS = CUSTOMPRODUCT, CANTIDAD
    PRICE OF PRODUCTS WITHOUT IVA AND WITHOUT SHIPPING
    PRICE OF PRODUCTS WITH IVA AND WITHOUT SHIPPING
    TOTAL PRICE
*/



